// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package carshop

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// WorkOrderServiceClient is the client API for WorkOrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkOrderServiceClient interface {
	RegisterWorkOrder(ctx context.Context, in *WorkOrderRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	GetRunningWorkOrders(ctx context.Context, in *RunningWorkOrdersQuery, opts ...grpc.CallOption) (*RunningWorkOrdersResponse, error)
	StartWorkOrderService(ctx context.Context, in *StartWorkOrderServiceRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	FinishWorkOrderService(ctx context.Context, in *FinishWorkOrderServiceRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	EndWorkOrder(ctx context.Context, in *EndWorkOrderRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type workOrderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkOrderServiceClient(cc grpc.ClientConnInterface) WorkOrderServiceClient {
	return &workOrderServiceClient{cc}
}

func (c *workOrderServiceClient) RegisterWorkOrder(ctx context.Context, in *WorkOrderRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/com.aviebrantz.carshop.WorkOrderService/RegisterWorkOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workOrderServiceClient) GetRunningWorkOrders(ctx context.Context, in *RunningWorkOrdersQuery, opts ...grpc.CallOption) (*RunningWorkOrdersResponse, error) {
	out := new(RunningWorkOrdersResponse)
	err := c.cc.Invoke(ctx, "/com.aviebrantz.carshop.WorkOrderService/GetRunningWorkOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workOrderServiceClient) StartWorkOrderService(ctx context.Context, in *StartWorkOrderServiceRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/com.aviebrantz.carshop.WorkOrderService/StartWorkOrderService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workOrderServiceClient) FinishWorkOrderService(ctx context.Context, in *FinishWorkOrderServiceRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/com.aviebrantz.carshop.WorkOrderService/FinishWorkOrderService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workOrderServiceClient) EndWorkOrder(ctx context.Context, in *EndWorkOrderRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/com.aviebrantz.carshop.WorkOrderService/EndWorkOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkOrderServiceServer is the server API for WorkOrderService service.
// All implementations should embed UnimplementedWorkOrderServiceServer
// for forward compatibility
type WorkOrderServiceServer interface {
	RegisterWorkOrder(context.Context, *WorkOrderRequest) (*empty.Empty, error)
	GetRunningWorkOrders(context.Context, *RunningWorkOrdersQuery) (*RunningWorkOrdersResponse, error)
	StartWorkOrderService(context.Context, *StartWorkOrderServiceRequest) (*empty.Empty, error)
	FinishWorkOrderService(context.Context, *FinishWorkOrderServiceRequest) (*empty.Empty, error)
	EndWorkOrder(context.Context, *EndWorkOrderRequest) (*empty.Empty, error)
}

// UnimplementedWorkOrderServiceServer should be embedded to have forward compatible implementations.
type UnimplementedWorkOrderServiceServer struct {
}

func (UnimplementedWorkOrderServiceServer) RegisterWorkOrder(context.Context, *WorkOrderRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterWorkOrder not implemented")
}
func (UnimplementedWorkOrderServiceServer) GetRunningWorkOrders(context.Context, *RunningWorkOrdersQuery) (*RunningWorkOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRunningWorkOrders not implemented")
}
func (UnimplementedWorkOrderServiceServer) StartWorkOrderService(context.Context, *StartWorkOrderServiceRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartWorkOrderService not implemented")
}
func (UnimplementedWorkOrderServiceServer) FinishWorkOrderService(context.Context, *FinishWorkOrderServiceRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinishWorkOrderService not implemented")
}
func (UnimplementedWorkOrderServiceServer) EndWorkOrder(context.Context, *EndWorkOrderRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndWorkOrder not implemented")
}

// UnsafeWorkOrderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkOrderServiceServer will
// result in compilation errors.
type UnsafeWorkOrderServiceServer interface {
	mustEmbedUnimplementedWorkOrderServiceServer()
}

func RegisterWorkOrderServiceServer(s *grpc.Server, srv WorkOrderServiceServer) {
	s.RegisterService(&_WorkOrderService_serviceDesc, srv)
}

func _WorkOrderService_RegisterWorkOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkOrderServiceServer).RegisterWorkOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.aviebrantz.carshop.WorkOrderService/RegisterWorkOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkOrderServiceServer).RegisterWorkOrder(ctx, req.(*WorkOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkOrderService_GetRunningWorkOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunningWorkOrdersQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkOrderServiceServer).GetRunningWorkOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.aviebrantz.carshop.WorkOrderService/GetRunningWorkOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkOrderServiceServer).GetRunningWorkOrders(ctx, req.(*RunningWorkOrdersQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkOrderService_StartWorkOrderService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartWorkOrderServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkOrderServiceServer).StartWorkOrderService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.aviebrantz.carshop.WorkOrderService/StartWorkOrderService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkOrderServiceServer).StartWorkOrderService(ctx, req.(*StartWorkOrderServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkOrderService_FinishWorkOrderService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishWorkOrderServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkOrderServiceServer).FinishWorkOrderService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.aviebrantz.carshop.WorkOrderService/FinishWorkOrderService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkOrderServiceServer).FinishWorkOrderService(ctx, req.(*FinishWorkOrderServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkOrderService_EndWorkOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndWorkOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkOrderServiceServer).EndWorkOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.aviebrantz.carshop.WorkOrderService/EndWorkOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkOrderServiceServer).EndWorkOrder(ctx, req.(*EndWorkOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WorkOrderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.aviebrantz.carshop.WorkOrderService",
	HandlerType: (*WorkOrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterWorkOrder",
			Handler:    _WorkOrderService_RegisterWorkOrder_Handler,
		},
		{
			MethodName: "GetRunningWorkOrders",
			Handler:    _WorkOrderService_GetRunningWorkOrders_Handler,
		},
		{
			MethodName: "StartWorkOrderService",
			Handler:    _WorkOrderService_StartWorkOrderService_Handler,
		},
		{
			MethodName: "FinishWorkOrderService",
			Handler:    _WorkOrderService_FinishWorkOrderService_Handler,
		},
		{
			MethodName: "EndWorkOrder",
			Handler:    _WorkOrderService_EndWorkOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workorder.proto",
}
